source 'https://rubygems.org'
gem 'better_errors', group: :development
gem 'bootstrap-sass'
gem 'bootstrap_form'
gem 'cancancan'
gem 'carrierwave'
gem 'cloudinary'
gem 'coffee-rails', '~> 4.1.0'
gem 'devise'
gem 'ffaker'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'mini_magick'
gem 'pg', '~> 0.21'
gem 'pry', group: :development
gem 'pry-nav', group: :development
gem 'pry-rails', group: :development
gem 'pry-remote', group: :development
gem 'pry-stack_explorer', group: :development
gem 'puma'
gem 'quiet_assets', group: :development
gem 'rails', '4.2.11.1'
gem 'rails_12factor', group: :production
gem 'rails_admin'
gem 'rolify'
gem 'rubycritic', require: false
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'spring', group: :development
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'web-console', group: :development